deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Download build artifacts
    uses: actions/download-artifact@v4
    with:
      name: build-${{ github.run_number }}
      path: build

  - name: Copy files to EC2
    uses: appleboy/scp-action@v0.1.4
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      source: "build/*"
      target: "/home/ubuntu/app/"

  - name: Restart app
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        cd /home/ubuntu/app/build
        npm install
	pm2 start node --name "myapp" -- src/app.js

